adds template field to api response
twitchdev/twitch-cli pull request #91
Opened 2021-08-13 22:39 UTC by aidenwallis

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

## Problem/Feature

With the addition of the `template` field on `/chat/emotes?broadcaster_id=`, there is a `template` field added to the API response, but isn't shown in `twitch api` calls. This adds it to the model so that it can unmarshal it.

## Description of Changes: 

- Adds template response

## Checklist

- [ ] My code follows the [Contribution Guide](https://github.com/twitchdev/twitch-cli/blob/master/CONTRIBUTING.md#Requirements)
- [x] I have self-reviewed the changes being requested
- [x] I have made comments on pieces of code that may be difficult to understand for other editors
- [x] I have updated the documentation (if applicable)

2021-08-13 23:13 UTC, zneix requested changes
This doesn't fix the issue, because inside `internal/api/api.go` full response from `apiResponse` variable is assigned to `data` only on non-2xx codes:
https://github.com/twitchdev/twitch-cli/blob/7328a881e4b694653ec287ba87886893cf2cca23/internal/api/api.go#L104-L107
In all other scenarios, only `data.Data` is set and thus only content of the "data" array from the actual Helix call is returned and show to user.
Given that, fields other than the "data" array will never be returned. I believe Twitch just didn't expect any other fields than data be returned on 2xx responses (unlike it was done in Kraken).

So anyway, a fix that makes it, so other fields than `data` can be returned would have to be made for this PR to work properly ;)

2021-08-14 03:50 UTC, aidenwallis commented
fixed, ty @zneix

2021-08-14 13:47 UTC, lleadbet approved these changes

2021-08-14 13:48 UTC, merged

2021-08-14 13:52 UTC, lleadbet commented
Thanks for the fix, @aidenwallis! Will cut a release next week to include this.